language: node_js
node_js:
  - "10" 
branches:
  only:
  - master 
cache:
  directories:
    - node_modules  
deploy:
  provider: pages
  skip_cleanup: true  
  keep_history: true
  github_token: 2b10af1ac82391bcd37a4ca5b53ca01d111cd022
script:
  - npm test
  - npm run build

    