language: node_js
node_js:
  - "10" 
branches:
  only:
  - master 
cache:
  directories:
    - node_modules  
deploy:
  provider: pages
  skip_cleanup: true  
  keep_history: true
 script:
  - npm test
  - npm run build

    