language: node_js
node_js:
  - "10"  
deploy:
  provider: pages
  skip_cleanup: true  
  keep_history: true
  github_token: 63de8c51a0a93a8c4df18d6ac03185e11b8d58df
script:
  - npm test
  - npm run build

    